### ISSUE TITLE
Camera and zoom control

### ISSUE THREAD

**Issue by andupotorac** [h-y1heng/StableMoFusion#2]
Hey there. This tool has an amazing potential to be used for OpenPose in diffusers. I'm wondering if the code allows controlling the camera angle, and zoom. So you could interface with the prompt to generate the movement, but also determine which angle and what zoom could be used when seeing the output.

**Comment by zhaowtVincent** [comment]
+1

**Comment by h-y1heng** [comment]
Hi, what you might want to achieve is to visualize the generated 3D motions from multiple perspectives and different zooms? This issue has nothing to do with our generation pipeline, but with 3D visualization. We save the generated motion results as relative xyz-coordinates (Y-up) in `.npy` file, which you can further transform to fit any world coordinate system, so you can see the output by rendering the 3D skeletons. Further, by adjusting the camera position, rotation and focal length during the rendering process, the visualization results of different zooms from multiple perspectives can be realized.

We recommend using Blender to do this, which we've successfully tried to modify the camera angle and zoom.  Our easy way is to clone the [mld repo](https://github.com/ChenFengYe/motion-latent-diffusion),  [set up Blender](https://github.com/ChenFengYe/motion-latent-diffusion#1-set-up-blender---wip) and [render the output directly](https://github.com/ChenFengYe/motion-latent-diffusion#2-optional-render-rigged-cylinders), without generating a mesh if you don't ask for it. The code allows controlling the camera angle and zoom lies in `motion-latent-diffusion-main/mld/render/blender/camera.py`：
![image](https://github.com/h-y1heng/StableMoFusion/assets/100835198/c9409d7d-933e-47f4-ab3c-57231c3d5fad)

BTW, we're eager for future work to further enhance our methods.  Feel free to share our work with others and encourage collaboration.

**Comment by andupotorac** [comment]
Thanks! Another question - how would your 3d model movements be passed to blender? As frames or?

**Comment by h-y1heng** [comment]
> Thanks! Another question - how would your 3d model movements be passed to blender? As frames or?

Yes,  because the generated output is an npy file of size  (nframes, njoints, 3), when you run blender with a python script in [mld](https://github.com/ChenFengYe/motion-latent-diffusion#2-optional-render-rigged-cylinders)，the skeleton joints will be processed frame by frame for rendering.

**Comment by andupotorac** [comment]
> 

Got it, thanks a lot!
