### ISSUE TITLE
Maximum inference motion sequence length

### ISSUE THREAD

**Issue by Jungduri** [h-y1heng/StableMoFusion#7]
Hi, 

I am working on your paper, and testing different settings.

While doing, I found that your model can generate a sequence motion more than 9.8sec length.
I would like to know, do you observe the same phenomenon? 

I tested with a text prompt "A man is walking forward" and 60 sec. 
Motion changed direction several times in every 9.8(assuming). I think it can be a clue of this.

**Comment by h-y1heng** [comment]
> 你好，
> 
> 我正在研究你的论文，并测试不同的设置。
> 
> 在做的过程中，我发现你的模型可以生成超过 9.8 秒的序列运动。 我想知道，你是否观察到了同样的现象？
> 
> 我使用文本提示“一个人正在向前走”和 60 秒进行了测试。 运动每 9.8 秒改变方向几次（假设）。我认为这可以作为线索。

是的，理论上可以生成任意长度的的运动序列，且应该保持和训练集一样频率（即HumanML3D20fps）。但由于在训练时设置的序列最大长度是9.8s，所以建议生成序列不要太长，过长可能导致“一个人正在向前走”提示生成的运动每 9.8 秒改变方向几次这种情况。
